title: Jian-Ci Xiao
logo: /assets/img/jcxiao_logo2.jpg
description: This is my personal website.
googlescholar: "https://scholar.google.com/citations?user=Ypz_3D4AAAAJ&hl=en"
#show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal

