title: Jian-Ci Xiao
logo: /assets/img/logo2.jpg
description: This is my personal website.
#show_downloads: false
#google_analytics:
google_scholar: "https://scholar.google.com/citations?user=Ypz_3D4AAAAJ&hl=en"
theme: jekyll-theme-minimal

