title: Jian-Ci Xiao
position: Postdoc
affiliation: CUHK
email: jcxiao (at) math.cuhk.edu.hk
logo: /assets/img/logo2.jpg
description: This is my personal website.
#show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal

